### ISSUE TITLE
Incorrect value of invested ETH for investor in angelRaise function

### ISSUE THREAD

**Issue by adamkolar** [bitcoinfriends/angel-contracts#4]
There are two errors in angelRaise function:

line 114
`    investments[msg.sender][_newRecordIndex].investedEthWei = msg.value;
`

line 130
`    angelFoundationAddress.transfer(msg.value * initialFundsReleaseNumerator / initialFundsReleaseDenominator);`

instead of `msg.value`, in both cases, there should be: `(msg.value - _notProcessedEthWei)` used because that's the true investment for the last investor who oversteps the `icoCap`

These errors have two possible implications:

- investor is able to withdraw more than he has invested, effectively stealing funds from the contract, due to breaking of this check:

```
      if (_recordRefundedEthWei > (investments[_investor][_recordID].investedEthWei - investments[_investor][_recordID].refundedEthWei)) {
        // this can happen due to rounding error
        _recordRefundedEthWei = (investments[_investor][_recordID].investedEthWei - investments[_investor][_recordID].refundedEthWei);
      }
```

- owner is paid more ETH than he should, possibly breaking refunding mechanism

**Comment by bitcoinfriends** [comment]
Hi Adam,

Thank you very much for pointing out this bug in our smart contract, which has now been rectified.

However, someone else had already pointed out this bug over here in our official bug hunting thread:

https://www.reddit.com/r/ethdev/comments/7e2h30/up_to_15_ether_bug_hunt_for_upcoming_angel_token/dq3dr4i/

We very much appreciate you taking the time to review our smart contract, and for pointing out this bug to us! 

Thank you!

**Comment by adamkolar** [comment]
That was also me, I filed the report in two places.

**Comment by bitcoinfriends** [comment]
Aha, thank you for letting us know. 

The code is still under audit at the moment.

**Comment by bitcoinfriends** [comment]
We have only just recently finalized our official code audit. 

The auditor agreed with your view point that although this bug would likely have been difficult to take advantage of, and that it would difficult for someone with malicious intent to gain anything substantial financially from it, the bug was sufficiently serious that it warrants a higher reward than 1.5 ETH.

**We have therefore decided to increase the reward from 1.5 ETH to 3.5 ETH**

We want you to know that we REALLY appreciate your input and your effort in this bug hunt, and the bug that you found was obviously the most significant one that was found during this entire process.

I understand from your earlier comments that you may not be completely satisfied, despite us doubling the reward. Hopefully however you accept that at least we have listened to your argument and tried in good faith to find a more suitable reward for your input. 

Had this bug been possible to exploit by _anyone_, rather than **JUST the absolute _last_ investor in a sold out ICO** we would obviously have paid out the full reward or much closer to it.

I will get the 3.5 ETH sent to you in the next few minutes, and I would appreciate if you can confirm receipt of them at least in the Reddit Bug Hunt thread.

Thanks again for all your hard and _skilled_ work! :)

**Comment by bitcoinfriends** [comment]
adamkolar has confirmed here: https://www.reddit.com/r/ethdev/comments/7e2h30/up_to_15_ether_bug_hunt_for_upcoming_angel_token/dq8butb/ that he received his reward of 3.5 ETH for the bug he found, so I am closing this issue.
